version: '2'

services:
  webserver:
    build: 
      context: ./
      dockerfile: docker/apache/Dockerfile
    container_name: athens-apache
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./:/var/www/html
      - ./docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
      - ./logs/apache2:/var/log/apache2
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: athens-mysql
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: athensrentals
      MYSQL_USER: athens
      MYSQL_PASSWORD: 1234aA
    ports:
      - "3306:3306"